### ISSUE TITLE
Doubt about how to run atom finder

### ISSUE THREAD

**Issue by jessica-amaral-alencar** [dgopstein/atom-finder#17]
Hello, my name is Jéssica Amaral and I am a Computer Engineering student at Federal University of Pernambuco, Brazil. I am trying to use the atom finder as a tool for a research project but I am having some problems to use it. I don't know if this is the right place to look for some help, but I didn't find other way to contact you. I installed the Leiningen as requested and I have java 10 installed on my computer. I ran the 'lein test' and it was successful, however when I run the atom finder it won't let me put the commands for it to work. I tried to use sublime REPL too and it doesn't recognise the commands.  I'm not very familiar with clojure, could you help me clarify how to make the atom-finder work?
P.S.: The repl results are attached.
![repl results](https://user-images.githubusercontent.com/39702842/41206932-d3e11ede-6ce2-11e8-9d48-da8f177722f0.png)
![repl results 2](https://user-images.githubusercontent.com/39702842/41206931-d3bb1860-6ce2-11e8-81d1-bf6d9907b595.png)

**Comment by dgopstein** [comment]
Hi Jéssica,

Glad to see you're trying to work with this project! I think this is a good way to express problems with the code/documentation since it allows others to learn from our mistakes/solutions.

It looks like you've found two problems with my code/documentation. I've updated the repo to fix the problems I think I had. Could you please try running the project again (start a REPL, then input `(parse-source "int main() { 1 + 1; }")`) and then reply here whether or not it worked?

Thanks!

For specific details about what was wrong, here are my theories:

1) The proper namespaces for parsing code are not imported by default: I recently refactored a lot of the parsing/AST-manipulation code into a separate library (clj-cdt)[https://github.com/dgopstein/clj-cdt], and as a result that library must be imported before use. I've added the imports by default in `atom-finder.core`, so it should work by default from the REPL now.

2) My documentation implies that `(parse-source "int main() { 1 + 1; }") => CPPASTTranslationUnit` is a valid piece of clojure code, but it's not. That snippet is actually trying to indicate that if you run the code `(parse-source "int main() { 1 + 1; }")` then the result will be a value of type `CPPASTTranslationUnit`. I've updated the documentation to put the indication of the result into a comment, so that if you copy-paste the snippet into your REPL it should still work fine

**Comment by jessica-amaral-alencar** [comment]
It worked!! Thank you very much!!!

**Comment by dgopstein** [comment]
No problem. Please reach out if you have any other problems/questions.
