### ISSUE TITLE
Finding atoms in directories

### ISSUE THREAD

**Issue by jessica-amaral-alencar** [dgopstein/atom-finder#18]
Hi, I'm having a problem with the "find-atoms-in-dirs" function, when I put it to run using the lein command and the directory address, it runs but doesn't print anything. Could you help me solve this please?

Here's an image of what's happening: (https://user-images.githubusercontent.com/39702842/45249395-f449a980-b2f5-11e8-9c4f-6878715e4d28.png)

**Comment by dgopstein** [comment]
Hi Jessica, after you run the command as shown in the screenshot, is there any data in the file `atoms.edn`? If so, what does it look like?

**Comment by jessica-amaral-alencar** [comment]
It's totally blank. Do you think I'm doing something wrong?

**Comment by dgopstein** [comment]
I just tested the same command on my machine and I did see output in `atoms.edn`, so maybe there's something different about your configuration. Are you sure there are C files in the directory you're passing? Sometimes I use the following command to see which relevant files are in a directory:

    find ~/codes -type f \( -name '*.c' -o -name '*.cc' -o -name '*.cpp' -o -name '*.cxx' -o -name '*.c++' -o -name '*.C' -o -name '*.h' -o -name '*.hh' -o -name '*.hpp' -o -name '*.h++' -o -name '*.H' -o -name '*.ipp' \)

If there are files that match that query, then maybe it'd make sense to search for atoms within those individual files. Let me know what that command prints, and we can go from there.

**Comment by jessica-amaral-alencar** [comment]
It's working! I was putting the wrong name of the directory. But I didn't know the output would go to the .edn file, I thought it would appear in the terminal. Thank you very much again!!

**Comment by dgopstein** [comment]
Glad to hear it's working!

In the command: `lein find-atoms-in-dirs dir > atoms.edn`, only the beginning part `lein find-atoms-in-dirs dir` runs my code. The second part `> atoms.edn`, means that all the terminal output gets put into the file `atoms.end` instead of on the screen. It's called [I/O redirection](http://homepages.uc.edu/~thomam/Intro_Unix_Text/IO_Redir_Pipes.html), in case you want to read more about it.

Let me know if you need any more help with this code.
